dashboardku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitoring_rekomendasi.urls')),
]

monitoring_rekomendasi/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import PelatihanUpdate, home, CustomLoginView, PelatihanList, PelatihanCreate, RekomendasiPelatihan

app_name = 'monitoring'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='monitoring:home'), name='logout'),

    path('', home, name='home'),
    path('pelatihan/', PelatihanList.as_view(), name='pelatihan'),
    path('pelatihan/create/', PelatihanCreate.as_view(), name='create-pelatihan'),
    path('pelatihan/update/<int:pk>/', PelatihanUpdate.as_view(), name='update-pelatihan'),
    
    path('rekomendasi/', RekomendasiPelatihan.as_view(), name='rekomendasi'),

]

monitoring_rekomendasi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



# Create your models here.
class Pelatihan(models.Model):
    nama_pelatihan = models.CharField(max_length=200)
    tanggal_mulai = models.DateField(null=True)
    tanggal_selesai = models.DateField(null=True)
    pic_pelatihan = models.ForeignKey(User, on_delete=models.CASCADE)
    rating_pelatihan = models.FloatField(null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.nama_pelatihan}"

class Rekomendasi(models.Model):
    choices = [('RB', 'Renbang'), ('EV', 'Evalap'), ('TU', 'TU'), ('PY', 'Penyelenggaraan')]
    deadline = timezone.now() + timezone.timedelta(7,0,0)

    nama_pelatihan = models.ForeignKey(Pelatihan, on_delete=models.CASCADE)
    deskripsi = models.TextField(null=True)
    penanggung_jawab = models.CharField(max_length=2, choices=choices, default='TU')
    diselesaikan = models.BooleanField(default=False)
    target_penyelesaian = models.DateField(default=deadline)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.nama_pelatihan} - {self.penanggung_jawab}"
    

monitoring_uat/models.py
from django.db import models

# Create your models here.

monitoring_rekomendasi/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.db.models import Avg

import wordcloud as wc

from .models import Pelatihan, Rekomendasi

class CustomLoginView(LoginView):
    template_name = "login.html"
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("monitoring:home")

def word_count(str):
    counts = dict()
    words = str.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    return counts

def home(request):
    pelatihan = Pelatihan.objects.all()
    avg_rating = pelatihan.aggregate(Avg('rating_pelatihan'))
    jum_pelatihan = pelatihan.count()

    sorted_pelatihan = pelatihan.order_by('rating_pelatihan')[:5]
    picked_pelatihan = []
    for i in sorted_pelatihan:
        temp = {}
        temp['nama'] = i.nama_pelatihan
        temp['rating'] = i.rating_pelatihan
        temp['ratio'] = (i.rating_pelatihan / 5) * 100
        picked_pelatihan.append(temp)

    # Get recommendation object
    rekomendasi = Rekomendasi.objects.filter(diselesaikan=False).count()

    # Get summ of ratings
    avg_rating = round(avg_rating['rating_pelatihan__avg'],2)
    percentage_rating = round(avg_rating/5 * 100, 2)

    test = Rekomendasi.objects.values_list('deskripsi', flat=True)
    test = " ".join(list(test)).lower()
    test = word_count(test)
    words = []
    for k, v in test.items():
        temp = {}
        temp["word"] = k
        temp["size"] = v * 15
        words.append(temp)
    # print(words)

    ## Pass context to template
    context = {
        'pelatihan' : picked_pelatihan,
        'jum_pelatihan' : jum_pelatihan,
        'avg_rating' : avg_rating,
        'avg_rating_percent' : percentage_rating,
        'need_attention': rekomendasi,
        'words': words,
    }

    return render(request, 'main.html', context)

class PelatihanList(LoginRequiredMixin, ListView):
    model = Pelatihan
    context_object_name = "pelatihan"
    template_name = 'daftar_pelatihan.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        ## Search feature
        # context['pelatihan'] = context['pelatihan'].filter(user=self.request.user)
        # context['count_incomplete'] = context['tasks'].filter(complete=False).count()

        # search_input = self.request.GET.get('search-area') or ''
        # if search_input:
        #     context['tasks'] = context['tasks'].filter(
        #         title__icontains=search_input)
        
        # context['search_input'] = search_input

        return context

class PelatihanCreate(LoginRequiredMixin, CreateView):
    model = Pelatihan
    fields = "__all__"
    context_object_name = "pelatihan"
    template_name = "form_pelatihan.html"
    success_url = reverse_lazy('monitoring:pelatihan')

class PelatihanUpdate(LoginRequiredMixin, UpdateView):
    model = Pelatihan
    fields = "__all__"
    success_url = reverse_lazy('monitoring:pelatihan')
    template_name = "form_pelatihan.html"

class RekomendasiPelatihan(ListView):
    model = Rekomendasi
    context_object_name = 'rekomendasi'
    template_name = 'daftar_rekomendasi.html'

monitoring_uat/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Evalapku - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    
    {% comment %} Charts {% endcomment %}
    <!-- Load d3.js -->
    <script src="https://d3js.org/d3.v4.js"></script>

    <!-- Load d3-cloud -->
    <script src="https://cdn.jsdelivr.net/gh/holtzy/D3-graph-gallery@master/LIB/d3.layout.cloud.js"></script>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

    {% if user.is_authenticated %}
        {% include "sidebar.html" %}
    {% endif %}
        

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                {% include "top_nav.html" %}

                {% block content %}
                
                {% endblock content %}


            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ekos 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Konfirmasi logout!</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Apakah anda yakin untuk logout?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                    <a class="btn btn-primary" href="{% url "monitoring:logout" %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    {% include "scripts.html" %}
    
</body>

</html>

templates/daftar_pelatihan.html
{% extends "base.html" %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Daftar Pelatihan</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nama Pelatihan</th>
                            <th>Tanggal Mulai</th>
                            <th>Tanggal Selesai</th>
                            <th>PIC Pelatihan</th>
                            <th>Rating Pelatihan</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Nama Pelatihan</th>
                            <th>Tanggal Mulai</th>
                            <th>Tanggal Selesai</th>
                            <th>PIC Pelatihan</th>
                            <th>Rating Pelatihan</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for pelatihan in pelatihan %}
                        <tr>
                            <td>{{ pelatihan.nama_pelatihan }}</td>
                            <td>{{ pelatihan.tanggal_mulai }}</td>
                            <td>{{ pelatihan.tanggal_selesai }}</td>
                            <td>{{ pelatihan.pic_pelatihan }}</td>
                            <td>{{ pelatihan.rating_pelatihan }}</td>
                            <td><a href="{% url 'monitoring:update-pelatihan' pelatihan.pk %}" class="btn btn-info mx-1">Edit</a>
                                <a href="#" class="btn btn-danger mx-1">Delete</a></td>

                        </tr>
                        
                        {% endfor %}
                        
                    </tbody>
                </table>

                <a href="{% url 'monitoring:create-pelatihan' %}" class="btn btn-success">Tambah Pelatihan</a>
            </div>
        </div>
    </div>

{% endblock content %}

templates/daftar_rekomendasi.html
{% extends "base.html" %}

{% block content %}
    <style>
    a {decoration:None;}
    </style>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Daftar Rekomendasi</h6>
        </div>
        <div class="card-body">
            <div class="row">
            {% for r in rekomendasi %}
                <div class="col-md-6 mb-4">
                    <a href="#" style="{text-decoration: None;}">
                    <div class="card {% if r.diselesaikan %}border-left-success{% else %}border-left-warning{% endif %} shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                        {{r.nama_pelatihan}}</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{r.deskripsi}}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-comments fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>                
            {% endfor %}

            </div>
        </div>
        
    </div>

{% endblock content %}

templates/form_pelatihan.html
{% extends "base.html" %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tambah Pelatihan</h6>
        </div>
        <div class="card-body">
            <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{% url 'monitoring:home' %}" class="btn btn-secondary">Kembali</a>
            <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>

{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
    <div class="card p-5 my-3">
        <h1 class='mb-3'>Login</h1>

        <form action="" method="post" class='mb-3'>
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Login">
        </form>

        <p>Untuk membuat akun silakan <a href="#">hubungi administrator</a></p>
    </div>
    
    </div>
    
{% endblock content %}

templates/scripts.html
{% load static %}

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
<script src="{% static 'js/charts/pie.js' %}"></script>
<script src="{% static 'js/charts/pie2.js' %}"></script>
<script src="{% static 'js/charts/pie3.js' %}"></script>

templates/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'monitoring:home' %}">
        <div class="sidebar-brand-icon">
            <i class="fab fa-korvue"></i>
        </div>
        <div class="sidebar-brand-text mx-3">DashKu</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url "monitoring:home" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Monitoring Rekomendasi Pelatihan
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Pelatihan</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Lihat data pelatihan:</h6>
                <a class="collapse-item" href="{% url 'monitoring:pelatihan' %}">Daftar Pelatihan</a>
                <a class="collapse-item" href="{% url 'monitoring:rekomendasi' %}">Daftar Rekomendasi</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Utilities Collapse Menu -->
    <div class="sidebar-heading">
        Milk UAT
    </div>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Rekomendasi</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Monitoring Rekomendasi:</h6>
                <a class="collapse-item" href="{% url 'monitoring:rekomendasi' %}">Daftar Rekomendasi</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

templates/top_nav.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-dark" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        {% if user.is_authenticated %}
            {% include "user.html" %}
        {% else %}
            <a href="{% url 'monitoring:login' %}" class="btn btn-dark">Login</a>
        {% endif %}
        

    </ul>

</nav>
<!-- End of Topbar -->

templates/user.html
{% load static %}

<!-- Nav Item - User Information -->
<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Hello, {{ user.username }}</span>
        <img class="img-profile rounded-circle"
            src="{% static 'img/undraw_profile.svg' %}">
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
        </a>
        <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
        </a>
        <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
        </a>
    </div>
</li>